server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8081
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-order
            - JwtAuthFilter
        - id: basket-service
          uri: http://localhost:8082
          predicates:
            - Path=/basket/**
#            - Header=Authorization, Bearer (.*)
          filters:
            - StripPrefix=1
            - PrefixPath=/market-basket
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8086
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
